language: java
jdk:
	- oraclejdk8
deploy:
 	provider: heroku
	api_key:
		secure: f2d7e482-f6a1-4fbf-b12b-fabba407e57d
	app: sistemaflashcards
	on:
		repo: sergiopsinformatico/FLASHCARDS
		branch: master